---
version: '3'

services:
  dbt:
    image: entechlog/dbt${DBT_VERSION_TAG}
    container_name: dbt
    build: ./docker/dbt/dbt_postgress_only
#    env_file:
#      - ./docker/dbt/.env
    command: 
      - bash 
      - -c    
      - |
        echo "Launching dbt"
        #
        sleep infinity
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${PWD}/dbt_docker_dir   # Uses the current working directory as the source
        target: /dbt_root
    ports:
      - "8085:8085"
    environment:
      - TZ=Etc/GMT
